version: "3.7"

services: 
# Eureka discovery service
  discovery: 
    image: shoppingcart-discovery-service
    ports: 
      - 8761:8761
      
# Gateway service
  gateway:
    image: shoppingcart-gateway-service
    ports:
      - 8082:8082
    restart: on-failure 
    healthcheck:  
     test: ["CMD", "curl", "-f", "http://discovery:8761"]
     start_period: 50s
    depends_on: 
        # TODO: wait for eureka server to up (https://github.com/Eficode/wait-for)
       - discovery
    environment: 
      eureka_client_serviceurl_defaultZone: http://discovery:8761/eureka
      
# Product service      
  product_service:
    image: shoppingcart-product-service
    ports:
      - 8084:8084
    depends_on: 
       - discovery
    environment: 
      eureka_client_serviceurl_defaultZone: http://discovery:8761/eureka
      spring_datasource_url: jdbc:mysql://host.docker.internal:3306/event-driven-shopping
      axon_axonserver_servers: host.docker.internal:8124 
